name: Build and Deploy

on:
  push:
    branches:
      - main # Modify this if you're using a different main branch name
    paths: client/**
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Change folder
        run: cd client

      - name: Install Dependencies
        run: npm install
        working-directory: ./client

      - name: Build React App
        run: npm run build
        working-directory: ./client
        env:
          VITE_APP_MOVIE_API_KEY: ${{ secrets.VITE_APP_MOVIE_API_KEY }}
          VITE_APP_API_ADDRESS: ${{ secrets.VITE_APP_API_ADDRESS }}
          VITE_APP_GOOGLE_CLIENT_ID: ${{ secrets.VITE_APP_GOOGLE_CLIENT_ID }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
